while True:
    print()
    response = input("Lastly, would you like any sides with that? ")
    print()
    print("┏━━━━━━━━━━━━━━━━━━━━━━━━━━┑")
    print("┃        sides             ┃")
    print("┃        ▔▔▔▔▔▔            ┃")
    print("┃ 1. Potato Wedges   $12  ┃")
    print("┃ 2. Margherita       $12  ┃")
    print("┃ 3. Pepperoni        $12  ┃")
    print("┃ 4. Vegetarian       $13  ┃")
    print("┃ 5. Beef and Onion   $13  ┃")
    print("┃ 6. Meat Lovers      $14  ┃")
    print("┖━━━━━━━━━━━━━━━━━━━━━━━━━━┛")